data_types = {
    # Events
    "end timestamp [ns]": "int64",
    "duration [ms]": "Int64",
    # Gaze
    "gaze x [px]": float,
    "gaze y [px]": float,
    "worn": "Int32",
    "fixation id": "Int32",
    "blink id": "Int32",
    "azimuth [deg]": float,
    "elevation [deg]": float,
    # 3D eye states
    "pupil diameter left [mm]": float,
    "pupil diameter right [mm]": float,
    "eyeball center left x [mm]": float,
    "eyeball center left y [mm]": float,
    "eyeball center left z [mm]": float,
    "eyeball center right x [mm]": float,
    "eyeball center right y [mm]": float,
    "eyeball center right z [mm]": float,
    "optical axis left x": float,
    "optical axis left y": float,
    "optical axis left z": float,
    "optical axis right x": float,
    "optical axis right y": float,
    "optical axis right z": float,
    # IMU
    "gyro x [deg/s]": float,
    "gyro y [deg/s]": float,
    "gyro z [deg/s]": float,
    "acceleration x [g]": float,
    "acceleration y [g]": float,
    "acceleration z [g]": float,
    "roll [deg]": float,
    "pitch [deg]": float,
    "yaw [deg]": float,
    "quaternion w": float,
    "quaternion x": float,
    "quaternion y": float,
    "quaternion z": float,
    # Blinks
    "blink id": "Int32",
    # Fixations
    "fixation id": "Int32",
    "end timestamp [ns]": "Int64",
    "duration [ms]": "Int64",
    "fixation x [px]": float,
    "fixation y [px]": float,
    # Saccades
    "saccade id": "Int32",
    "amplitude [px]": float,
    "amplitude [deg]": float,
    "mean velocity [px/s]": float,
    "peak velocity [px/s]": float,
    # Events
    "name": str,
    "type": str,
}
